"""sync quiz_scores with user.db

Revision ID: 2a29222dc7ef
Revises: d551cd5a8818
Create Date: 2025-07-16 02:19:50.329403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a29222dc7ef'
down_revision: Union[str, Sequence[str], None] = 'd551cd5a8818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
